### PR TITLE
Fix species page link if there is no # at the end of the URL

### LINKED ISSUE #49: I sometimes get a 404 link to `https://www.mammaldiversity.org/explore.htmlgenus=Zaglossus&species=attenboroughi&id=1000003` (notice missing `?` after `explore.html`) if I go to "Search species", start typing "Zagl", and click one of the species. Sometimes it goes to this 404 link and sometimes it correctly shows the species account.
Thanks! It's inconsistent, but I sometimes get a 404 link to `https://www.mammaldiversity.org/explore.htmlgenus=Zaglossus&species=attenboroughi&id=1000003` (notice missing `?` after `explore.html`) if I go to "Search species", start typing "Zagl", and click one of the species. Sometimes it goes to this 404 link and sometimes it correctly shows the species account.

_Originally posted by @JelleZijlstra in https://github.com/mammaldiversity/mammaldiversity.github.io/issues/24#issuecomment-1948916460_

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #49

### CODE REVIEW

File: js/filter.js [hunk 1]
```diff
@@ -52,7 +52,9 @@ function populateSpeciesInfo(results, speciesID, mddTable) {
       if (document.location.hash != "") {
           var permalink = document.URL;            
       } else {
-          var permalink = document.URL + "genus=" + speciesData.genus + "&" + "species=" + speciesData.specificEpithet + "&" + "id=" + speciesID;
+          // The current URL may or may not have a "#" at the end already. Handle both cases.
```
Comment (jhpoelen) [inline js/filter.js:55]: Nice! Why not use the new URL API https://developer.mozilla.org/en-US/docs/Web/API/URL#12 ?

Comment (JelleZijlstra) [reply js/filter.js:55]: Partly to avoid making too many changes at once, partly because I don't think what we're doing here (URL parameters but in the hash part of the URL) is what the standard APIs are designed for. I do agree that it's better to use modern APIs like that instead of treating URLs as raw strings.

Comment (jhpoelen) [reply js/filter.js:55]: I'll add some unit test for this . . . looks like a perfect case for some tests.

**Review by jhpoelen — APPROVED** [review]
thanks for your contribution - I suspect that my changes to load static data (from js/mdd.js) causes some load timing to change. Apologies for not testing this thoroughly, I'll try and add some unit tests.

File: js/filter.js (hunk 1 above)
Comment (JelleZijlstra) [reply js/filter.js:55]: Unit tests would be good, yes. I haven't looked at this codebase enough to see whether that would be easy to do.

Comment (jhpoelen) [reply js/filter.js:55]: some permalink unit tests can be found at https://github.com/mammaldiversity/mammaldiversity.github.io/tree/master/test .

**Comment by n8upham** [comment]
Hey @jhpoelen do I need to approve anything here or are we all set?
